#!/bin/bash


yum install -y git
git config --global user.email "Jeremy.Mordkoff@riftio.com"
git config --global user.name "Jeremy Mordkoff"
git config --global push.default simple

mkdir .ssh
cat <<EOF >.ssh/config
StrictHostKeyChecking no


host git
        user git
        forwardX11 no
        identityFile ~/.ssh/id_git

EOF

cat <<EOF >.ssh/id_git
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAycReMTCf0oDQRagaPmvxokzaWu4h7uBgUc06eJxUnfAO6zAU
RzPHL35+X7xXVONjEY27taMLY3KNaNAl15vKjcidb6PpFMWDLHQrlV5uipTbojgF
rkQ/tZ8PhPSVcoWsSSXJr0jZipIGRZnu3evd7b18qDBlj8eRLR6K2FZKAvVhygXe
Ele5eXEU/McqMh/Dm0ejJ4qp0BtiyEf5tFAUMNnNGt4WgiwQ9CGpdzt/kSfBSgIA
Cx/CEX5GeudpK3Ny2cYHpQGbbdangTzy7EOgG9bNkODM7dtFhmhYWRs9Cdy2xAQn
4I825PpaUYiJW9/G/bZvimgs/wVuLDve/TU+gwIBIwKCAQEAm6YcxtxeCMnFPQym
h+ze+Yu+Y2c+v5clu3Ju71QGwvsEMcYBA7o6klpEOzmFMttMbKCJfX3G9PH4Dwb4
nwMnOi0LvIXCbxwGGvqIBYNclsqazZjucH3Kv07RdTG1HdTVXP/kumtl/S7Ro2ge
qzJMHcywnwDDYEl+nyYwmEKQ3bSbEKH516stIOzc+1VkajzYVCOmQ4yIuqQD6uh3
Pwpq/3X1Rsu9Bw1970+P00t+1bKhq8k37biUZDAXPoU6CnY2eLPq35mL0Cc5Wv3S
CDfwTn8BePma3o9pgtbxDDTVcC2+mmV66ny3+8rP0q6uZeJ/vTALOwcXG+LPFT6n
ugVlcwKBgQD3b5uk1/28sn8ehynVNg5l9S/pMCAtsPKkXhwvLolIfn3RnAysf/jR
Au+jNNgF3A3bIv316UN2vK9K14qW5DI7ApDG40yvzh+3Hx106gbCISZroyRdbS2X
yv0kiy0AWsKZd09x1OQAoNWPtxaLgyOLi3Qdx93cvuNt3kQ3UPbTDQKBgQDQwBz+
1u3euLVvtI10AJMV0LobVAApsfVRCkDRIRgbEd+Ep8lPDAVQ12wS7h4OLk7Iuhul
MBLzRLaRp6ajfBBGkBMjQQpS1EG4/yJRTOrfXAu+1ahH7mWNQTghQtkoAT2hexS3
5S93LSdeY2mghBHhteeYiPxhs7AjRWQQnqkzzwKBgQCGUoexQg1mb4bWDtwx6iUS
xu4fgIZ/NCvy1ACr5hACyFLuIYM5EkU+Q2wlZdRa880B7mybcAANQduAZmEtV053
zjFWBlzUdzXJzw/9o51E0CrMt6YG1N48dYIbJvssFAM9XgaOQF6D/4ngTXKjgbQ1
z1xKrlPeO71KRXV9HVLKVwKBgGVkoF6Fpryi28iK5Z6+c1O9JzHYV9m81j1OH3uF
GlZKgoJC3h8Ud5xLYGD3UG1JsTzsrleMYPnQ6vZKHb0fAJdNSx/AgVtuaRC2b8EW
uzlJ9xOMWQz+w5xhganBYilfsDh9nFlSD72K9d1jfHKJSoOS3jQlR2Knu/Pf4CVU
YNAFAoGBAKU4EcntM5eA1EAsJ29i8GlB3e2+Q7JE1bPO98iAZEmYzew7+4yYN6Nd
8cJhaVM6YUb2K7AU1sLJtibi59NO/hJx1epLgyPMEPVe55IdFw91a479dmv2lP9G
Ma4ub/Xn1ReaRkZYnz/VZEQ598heAJ5hNLkf8EzS8v7iV/leDXjw
-----END RSA PRIVATE KEY-----
EOF

chmod 700 .ssh
chmod 600 .ssh/*

git clone git@git:rift.git
cd rift
git checkout lezz-mkvmimage
./scripts/vm_image/mkvmimg --container --modes ui
yum install -y riftware-launchpad
systemctl start rwlp
